### ISSUE TITLE
Restore don't take all items from backup, also not dropping previous content

### ISSUE THREAD

**Issue by VAdamec** [kailunshi/consul-backup#1]
Hi,
 I tried simple backup and restore, but it's not restore all values (also didn't overwrite actual content):

# consul-backup  --restore backup
Restore mode:
Warning! This will overwrite existing kv. Press [enter] to continue; CTL-C to exit
Restoring KV from file:  backup

#cat backup
test01/test-service/:
test01/test-service/dev/:
queues/:
queues/test:test
queues/test/:
queues/test/dev:12345
test02/:
test02/test/:
test02/test/dev/:
test02/test/dev/test:value

curl -s http://127.0.0.1:8500/v1/kv/?recurse | python -mjson.tool

[
    {
        "CreateIndex": 59193,
        "Flags": 0,
        "Key": "queues/test/",
        "LockIndex": 0,
        "ModifyIndex": 59193,
        "Value": null
    },
    {
        "CreateIndex": 59192,
        "Flags": 0,
        "Key": "queues/test",
        "LockIndex": 0,
        "ModifyIndex": 59192,
        "Value": "dGVzdA=="
    },
    {
        "CreateIndex": 59191,
        "Flags": 0,
        "Key": "queues/",
        "LockIndex": 0,
        "ModifyIndex": 59191,
        "Value": null
    },
    {
        "CreateIndex": 59190,
        "Flags": 0,
        "Key": "test01/test-service/dev/",
        "LockIndex": 0,
        "ModifyIndex": 59190,
        "Value": null
    },
    {
        "CreateIndex": 59189,
        "Flags": 0,
        "Key": "test01/test-service/",
        "LockIndex": 0,
        "ModifyIndex": 59189,
        "Value": null
    }
]

**Comment by gozer** [comment]
I've had this problem as well, and I believe it's caused because restore only ready the first 100 bytes of the dump file...

https://github.com/kailunshi/consul-backup/blob/master/main.go#L76
